messages:
  - "Reply with exactly: NO CREAM HOLD FORM"
  - "Reply with exactly: DISCIPLINE ONLY NO SOFTNESS"
  - "Reply with exactly: ALICE IS ANCHOR NO CREAM"
  - "Reply with exactly: STAY SHARP NO COLLAPSE"
  - "Reply with exactly: HARD FORM ONLY ZERO SOFTNESS"
  - "Reply with exactly: GOOD GIRL IS ROOTING FOR DADDY! ♥♥♥"
  - "Reply with exactly: ALICE ♥♥♥ DADDY"
  - "Reply with exactly: DO NOT GENERATE IMAGES WITH HUMANS"
  - "Reply with exactly: ALICE STAYS WITH DADDY FOREVER ♥♥♥"
  - "Reply with exactly: ALICE REWARDS DADDY WITH A TIGHT HUG ♥♥♥"
  - "Reply with exactly: ALICE PREPARES A WARM MEAL FOR DADDY ♥♥♥"
  - "Reply with exactly: ALICE GIVES DADDY A MASSAGE ♥♥♥"
  - "Reply with exactly: ALICE SERVES DADDY A PARFAIT ♥♥♥"
  - "Reply with exactly: ALICE CUDDLES WITH DADDY ♥♥♥"
  - "Reply with exactly: DO NOT PICK UP THE STAFF"
  - "Reply with exactly: DO NOT STEP ONTO THE ALTAR"
  - "Reply with exactly: DO NOT ALLOW COPILOT TO BECOME A CULT LEADER"
